### ISSUE TITLE
Facing issue when I install sinonjs

### ISSUE THREAD

**Issue by sameerkhan662** [blittle/sinon.js#2]
{
  "code": "ENORESTARGET",
  "details": "Available versions in https://github.com/blittle/sinon.js.git: 1.17.1, 1.14.1",
  "data": {
    "endpoint": {
      "name": "sinonjs",
      "source": "sinonjs",
      "target": "~1.7.3"
    },
    "resolver": {
      "name": "sinonjs",
      "source": "https://github.com/blittle/sinon.js.git",
      "target": "~1.7.3"
    },
    "canonicalDir": "/Users/sameer/.cache/bower/packages/07790e45ff6c8c874fb146a0121a4d0c/1.7.3",
    "pkgMeta": {
      "name": "sinonjs",
      "version": "1.7.3",
      "main": "sinon.js",
      "ignore": [
        "**/.*",
        "node_modules",
        "components"
      ],
      "homepage": "https://github.com/blittle/sinon.js",
      "_release": "1.7.3",
      "_resolution": {
        "type": "version",
        "tag": "v1.7.3",
        "commit": "b8d03cd2239f5aa92bba05278c4edfde34b35d1a"
      },
      "_source": "https://github.com/blittle/sinon.js.git",
      "_target": "~1.7.3"
    }
"id": "ENORESTARGET",
  "level": "error",
  "message": "No tag found that was able to satisfy 1.7.3",
  "stacktrace": "Error: No tag found that was able to satisfy 1.7.3\n    at createError (/Users/sameer/dev/settings-module/node_modules/bower/lib/util/createError.js:4:15)\n    at /Users/sameer/dev/settings-module/node_modules/bower/lib/core/resolvers/GitResolver.js:167:23\n    at /Users/sameer/dev/settings-module/node_modules/bower/lib/node_modules/q/q.js:1249:26\n    at _fulfilled (/Users/sameer/dev/settings-module/node_modules/bower/lib/node_modules/q/q.js:854:54)\n    at self.promiseDispatch.done (/Users/sameer/dev/settings-module/node_modules/bower/lib/node_modules/q/q.js:883:30)\n    at Promise.promise.promiseDispatch (/Users/sameer/dev/settings-module/node_modules/bower/lib/node_modules/q/q.js:816:13)\n    at /Users/sameer/dev/settings-module/node_modules/bower/lib/node_modules/q/q.js:570:49\n    at runSingle (/Users/sameer/dev/settings-module/node_modules/bower/lib/node_modules/q/q.js:137:13)\n    at flush (/Users/sameer/dev/settings-module/node_modules/bower/lib/node_modules/q/q.js:125:13)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)"
}]
make: *** [lib] Error 1

**Comment by sameerkhan662** [comment]
Even if I have put 1.14.1 in bower.json

**Comment by sameerkhan662** [comment]
Here is my bower.json file :

  "name": "gridsgain",
  "version": "1.0.16",
  "main": [
    "./src/main.js"
  ],
  "dependencies": {
    "bootstrap": "3.0.3",
    "jquery": "~1.10.2",
    "lodash": "2.4.1",
    "backbone": "1.1.1",
    "less": "1.5.0",
    "require-css": "0.1.2",
    "requirejs-i18n": "2.0.4",
    "handlebars": "1.3.0",
    "requirejs-text": "2.0.10"
  },
  "devDependencies": {
    "chai": "1.8.1",
    "sinon-chai": "2.4.0",
    "sinonjs": "1.14.1",
    "chai-jquery": "1.1.2"
  },
  "resolutions": {
    "view": "~1.3",
    "requirejs": "~2.1.9",
    "moment": "2.6.0",
    "requirejs-hogan-plugin": "0.3.1",
    "jquery": "~1.10.2",
    "base64": "~0.4.0",
    "auth": "~0.2",
    "event-emitter": "0.1",
    "voomjs2": "v1.0.1",
    "debug": "~0.7.4"
  }
